{% set name = "development-tools" %}
{% set version = "1.00" %}

package:
  name: 'refractor-{{ name|lower }}'
  version: '{{ version }}'

source:
  # No source, the is a meta package
  
build:
  #number: 1
  # Add constraint on fortran version for OSx
  #number: 2
  # Add pytz needed by Cris
  # number: 3
  # Add h5py and coreutils needed by oco
  number: 4

requirements:
  build:
  host:
  run:
    - {{ compiler('cxx') }}  
    - {{ compiler('c') }}  
    - {{ compiler('fortran') }}
    - cmake
    - pkg-config
    # https://github.com/ContinuumIO/anaconda-issues/issues/8812,
    # can't find -lgomp or -lquadmath without this. Will probably get
    # fixed at some point and we can remove this
    - libgcc-ng # [linux]
    # For right now, pin the fortran version to the one in pkgs/main
    # conda-forge has a newer one on the mac, but hold off switching
    - gfortran_osx-64 <=4.85 # [osx]
    - python {{ python }}
    - numpy
    - ninja-build
    - libboost
    - swig
    - doxygen
    - gsl
    - eigen
    - lua
    - luabind
    - libblitz
    - lidort
    - twostream
    - first_order
    - hdf5
    - netcdf4
    - python
    - jupyter
    - matplotlib
    - attrdict
    - ptpython
    - pytest
    - pytest-xdist
    - pytest-cov
    - pytest-runner
    - pytz
    - h5py
    - coreutils

about:
  summary: This is a metapackage that installs the tools to build the RT Retrieval Framework
    
