# Locate Twostream library


FIND_LIBRARY(_TWOSTREAM_LIBRARY
  NAMES twostream
  HINTS $ENV{TWOSTREAM_DIR} ${TWOSTREAM_DIR}
  PATH_SUFFIXES lib64 lib
)

IF(_TWOSTREAM_LIBRARY)
    SET(TWOSTREAM_LIBRARIES
        "${_TWOSTREAM_LIBRARY}" CACHE STRING "Twostream Libraries")
ENDIF(_TWOSTREAM_LIBRARY)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Twostream DEFAULT_MSG TWOSTREAM_LIBRARIES)
