# Locate First_order library


FIND_LIBRARY(_FIRST_ORDER_LIBRARY
  NAMES first_order
  HINTS $ENV{FIRST_ORDER_DIR} ${FIRST_ORDER_DIR}
  PATH_SUFFIXES lib64 lib
)

IF(_FIRST_ORDER_LIBRARY)
    SET(FIRST_ORDER_LIBRARIES
        "${_FIRST_ORDER_LIBRARY}" CACHE STRING "First_order Libraries")
ENDIF(_FIRST_ORDER_LIBRARY)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(First_order DEFAULT_MSG FIRST_ORDER_LIBRARIES)
