# Locate Blitz++ library

# We want to use the Conda version if it is available, and the user hasn't
# otherwise specified a different version
if(NOT BLITZ_DIR AND DEFINED ENV{CONDA_PREFIX})
  set(BLITZ_DIR $ENV{CONDA_PREFIX})
endif(NOT BLITZ_DIR AND DEFINED ENV{CONDA_PREFIX})

FIND_PATH(BLITZ_INCLUDE_DIR blitz/array.h
  HINTS $ENV{BLITZ_DIR} ${BLITZ_DIR}
  PATH_SUFFIXES include
)

FIND_LIBRARY(_BLITZ_LIBRARY
  NAMES blitz
  HINTS $ENV{BLITZ_DIR} ${BLITZ_DIR}
  PATH_SUFFIXES lib64 lib
)

IF(_BLITZ_LIBRARY)
    SET(BLITZ_LIBRARIES
        "${_BLITZ_LIBRARY}" CACHE STRING "Blitz++ Libraries")
ENDIF(_BLITZ_LIBRARY)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Blitz DEFAULT_MSG BLITZ_LIBRARIES BLITZ_INCLUDE_DIR)
